version: '3.4'

services:
  nightsheepapi:
    image: edwardzieminski/nightsheepapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
    networks:
      - traefik
    deploy:
      labels:
        # request Traefik to load this service
        - "traefik.enable=true"
        # docker network
        - "traefik.docker.network=traefik-for-nightsheepapi_default"
        # load balancer
        - "traefik.http.services.nightsheepapi.loadbalancer.server.port=5000"
        - "traefik.http.services.nightsheepapi.loadbalancer.server.scheme=http"
        # custom response headers
        - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.server=Traefik-for-NightSheepAPI"
        # router for HTTP
        - "traefik.http.routers.nightsheepapi-prod-http.rule=Host(`nightsheepapi.localhost`)"
        - "traefik.http.routers.nightsheepapi-prod-http.entrypoints=http-entry-point"
        - "traefik.http.routers.nightsheepapi-prod-http.service=nightsheepapi"
        - "traefik.http.routers.nightsheepapi-prod-http.middlewares=secure-headers"
networks:
  traefik:
    external:
      name: traefik-for-nightsheepapi_default