version: '3.4'

services:
  nightsheepapi:
    image: edwardzieminski/nightsheepapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5001
    networks:
      - traefik
    deploy:
      labels:
        # request Traefik to load this service
        - "traefik.enable=true"
        # docker network
        - "traefik.docker.network=traefik-for-nightsheepapi_default"
        # load balancer
        - "traefik.http.services.nightsheepapi-stg.loadbalancer.server.port=5001"
        - "traefik.http.services.nightsheepapi-stg.loadbalancer.server.scheme=http"
        # custom response headers
        - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.server=Traefik-for-NightSheepAPI"
        # router for HTTP
        - "traefik.http.routers.nightsheepapi-stg-http.rule=Host(`nightsheepapi-stg.localhost`)"
        - "traefik.http.routers.nightsheepapi-stg-http.entrypoints=http-entry-point"
        - "traefik.http.routers.nightsheepapi-stg-http.service=nightsheepapi-stg"
        - "traefik.http.routers.nightsheepapi-stg-http.middlewares=secure-headers"
networks:
  traefik:
    external:
      name: traefik-for-nightsheepapi_default